name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-github-codebuild-selfhosted-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build --platform linux/arm64 -t hello-world .

      - name: Run Docker container
        run: |
          docker run hello-world