name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-github-codebuild-selfhosted-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker buildx --platform linux/arm64 -t hello-world .